version: '3'
services:

  datastore:
    image: ldp-node
    networks:
      - private
    container_name: 'ldp-cli'
    working_dir: '/ot-ldp/'
    tty: true

  client:
    image: ldp-node
    networks:
      - private
    container_name: 'ldp-srv'
    working_dir: '/ot-ldp/'
    tty: true

networks:
 private:
